[package]
name = "euclide"
version = "0.1.0"
description = "Euclide - le bureau d'enseignement pour un professeur de mathématiques et NSI"
authors = ["Elliot Moreau"]
edition = "2021"

[lib]
name = "euclide_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset", "macos-private-api"] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-notification = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
chrono = "0.4"
base64 = "0.22"
uuid = { version = "1", features = ["v4"] }
window-vibrancy = "0.6"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_System_Power", "Win32_Foundation"] }

[profile.release]
opt-level = "s"
lto = true
strip = true
